### ISSUE TITLE
Seurat RPCA code for co-embedding?

### ISSUE THREAD

**Issue by biobenkj** [Jerby-Lab/HGSC_SpatialPerturbational#1]
Hello! Thanks so much for including all the code, supplemental methods, etc. as part of the paper! I'm particularly curious about the co-embedding that was done using the Seurat RPCA method and can't seem to find where this is located in the code base beyond importing the existing rds file from zenodo. Could you please point me to where this code is? Thanks so much and my apologies if I missed it!

**Comment by christineyyeh** [comment]
Hello @biobenkj, Thank you for your interest in our study! Given the large-scale nature of our study, we decided to release this repository to reproduce figures from intermediate files. The co-embedding was part of a preprocessing workflow and not included explicitly in this repo. However, our approach, as described in the paper, simply involved a wrapper around Seurat functionality. 

if `sub.list` is a list of preprocessed objects corresponding to each of the single cell or spatial transcriptomics datasets, and `n_dims` corresponds to the number of PCs you hope to use in the co-embedding, then, the integration code looks like this: 

```
  anchors <- FindIntegrationAnchors(object.list = sub.list,
                                    reduction = "rpca",
                                    dims = 1:n_dims,
                                    anchor.features = 800)
  ovarian.integrated <- IntegrateData(anchorset = anchors, dims = 1:n_dims)
  saveRDS(ovarian.integrated,
          file = "output.rds")
```

Hope this helps!

**Comment by biobenkj** [comment]
thank you so much! I greatly appreciate it as the co-embedding looked like it performed really well, but wasn't sure if there were additional options specified in the calls to define anchors. thanks again and congratulations on the paper!

**Comment by christineyyeh** [comment]
Hi @biobenkj! Thanks for closing the issue. Just a note: we believe part of the reason the co-embedding was successful was due to the fact that we sub-sampled only "high-confidence" cells from the ST data to co-embed with the single cell data. We had devised a an iterative subsampling procedure (described in the Supplement Information) that scores the confidence of the cell type assignment of every cell. I didn't want to mislead you; even though we did use the RPCA co-embedding "out of the box", based on our internal computational experiments, our preprocessing method had a lot to do with the success of the final co-embedding published in the study.
